# Generated by Django 6.0.1 on 2026-01-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_cve', models.CharField(max_length=50, unique=True)),
                ('titre_bulletin', models.CharField(max_length=500)),
                ('date_publication', models.DateField()),
                ('lien_bulletin', models.URLField(max_length=500)),
                ('base_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails', models.TextField()),
            ],
        ),
    ]
